server:
  port: 8080

spring:
  application:
    name: auth-service

  data:
    redis:
      host: host.docker.internal
      port: 6379
      database: 0
      password: ${REDIS_PASSWORD}

jwt:
  secret: "${JWT_SECRET}"

telegram:
  bot-token: "${TELEGRAM_BOT_TOKEN}"
  check-hash: true

logging:
  level:
    root: INFO
    com.example: INFO
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"